class DeviceTypes:
    BITBOX02 = "bitbox02"
    BITCOINCORE = "bitcoincore"
    COBO = "cobo"
    COLDCARD = "coldcard"
    ELECTRUM = "electrum"
    ELEMENTSCORE = "elementscore"
    GENERICDEVICE = "other"
    KEEPKEY = "keepkey"
    LEDGER = "ledger"
    SPECTERDIY = "specter"
    TREZOR = "trezor"
