name: Docker Image CI

on:
  push:
    branches: 
     - master 
     - docker_push
  pull_request:
    branches:
     - master

jobs:

  build-amd64:
    name: Build image (AMD64)
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set env variables
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
        IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
        echo "IMAGE_NAME=${IMAGE_NAME//docker-/}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
          docker build . \
          --file Dockerfile \
          --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$BRANCH-amd64