name: End-to-end tests
on: [push,pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: registry.gitlab.com/k9ert/specter-desktop/cypress-python:20201111231032
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - run: |
          python -V  # Print out python version for debugging
          apt update
          apt install -y libusb-1.0-0-dev libudev-dev # usb-support in hidapi
          pip3 install virtualenv
          virtualenv --python=python3 .env
          . ./.env/bin/activate
          pip3 install -e .
          pip3 install -r test_requirements.txt
          npm i
      - name: Cypress run 1
        run: ./utils/test-cypress.sh --docker --debug run
      - name: Cypress run 2
        uses: cypress-io/github-action@v2
